# name: Push image to Artifact when new tag is created

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   build-and-push:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Login Google Cloud with service account
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Configure Docker to use Artifact
#         run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

#       - name: Build Docker Image
#         run: |
#           IMAGE_NAME="asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/en-vocab-server"
#           TAG_NAME="${GITHUB_REF#refs/tags/}"
#           docker build -t "$IMAGE_NAME:$TAG_NAME" --secret id=github_token,env=GITHUB_TOKEN .
#           docker push "$IMAGE_NAME:$TAG_NAME"
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
